"""Admit the full recovered timing cohort, preserve old rows, plot all cases."""
import hashlib,io,json,statistics
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def main():
    folder=ROOT/'results/research/RENDER10_benchmark/recovered_20261009B';record=json.loads((folder/'receipt.json').read_bytes());old=json.loads((ROOT/'results/research/RENDER10_benchmark/original_20261009A/receipt.json').read_bytes());plan=json.loads((ROOT/'docs/research/RENDER10_benchmark_plan.json').read_bytes())
    assert record['status']=='completed_all_registered_RENDER10_workloads' and len(record['checks'])==77 and all(c['passed'] for c in record['checks']) and record['completed_rows_repeated']==0
    methods=['cuda_eager','cuda_graph','scalar_render','vector_render','render'];keys={(r['case'],r['block'],r['method']):r for r in record['rows']};expected={(c['name'],b,m) for c in plan['cases'] for b in range(7) for m in methods};assert len(record['rows'])==245 and set(keys)==expected
    for row in old['rows']:assert keys[(row['case'],row['block'],row['method'])]==row
    for name,digest in plan['source_sha256'].items():assert hashlib.sha256((ROOT/name).read_bytes()).hexdigest()==digest
    table=[];text=['# OpenGL 4.6: complete registered timing cohort','', 'All 245 registered rows and 77 output gates are complete. The original 143 rows are preserved exactly; only missing keys were measured. Recovery verifies identical registered input arrays and unchanged source. The interruption separates measurement sessions and qualifies interpretation: these are descriptive technical measurements on one GPU, not independent replications or confidence intervals.','', '| Workload | CUDA eager ms | CUDA Graph ms | Scalar fragment ms | Vector fragment ms | Compute ms | Best CUDA / compute |','|---|---:|---:|---:|---:|---:|---:|']
    for case in plan['cases']:
        values={m:[r['host_seconds']/r['repetitions']*1000 for r in record['rows'] if r['case']==case['name'] and r['method']==m] for m in methods};medians={m:statistics.median(v) for m,v in values.items()};ratio=min(medians['cuda_eager'],medians['cuda_graph'])/medians['render'];table.append(dict(case=case['name'],median_ms=medians,range_ms={m:[min(v),max(v)] for m,v in values.items()},best_cuda_over_compute=ratio));text.append('| '+case['name']+' | '+' | '.join(f'{medians[m]:.4f}' for m in methods)+f' | {ratio:.4f}× |')
    text.extend(['','Compute is faster in six point comparisons and slower for C48/grid128. C16/grid128 measures approximately 2.084× relative to the best CUDA comparator. Small differences may be sensitive to technical noise; no universal advantage is claimed.','', 'FP32, TF32 off, resident seeding, sixteen updates and full decoding are held fixed. CUDA eager and CUDA Graph remain strong comparators. Setup, compilation, transfers, training and complete system energy are outside this primary timing. Short counter deltas remain inadequate energy evidence.','', 'The separate sustained RENDER11 energy endpoint preserves 100/105 original blocks after a RAM-floor interruption; do not infer its complete comparative effect without all registered rows. Original failures and queue timeouts remain archived.'])
    (ROOT/'docs/research/RENDER10_results.md').write_text('\n'.join(text)+'\n',encoding='utf-8');summary=dict(status='verified_complete_registered_timing_cohort',rows=245,gates=77,original_rows_preserved=len(old['rows']),old_rows_repeated=0,interruption_qualified=True,table=table);(folder/'independent_summary.json').write_text(json.dumps(summary,indent=2)+'\n',encoding='utf-8')
    import matplotlib;matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from PIL import Image
    images=[];labels=['CUDA eager','CUDA Graph','Scalar fragment','Vector fragment','GL 4.6 compute'];colours=['#8096bb','#b2c1dd','#ca7b72','#67bcaa','#e5b769']
    for row in table:
        fig,ax=plt.subplots(figsize=(10,5));fig.patch.set_facecolor('#101722');ax.set_facecolor('#101722');ax.barh(labels,[row['median_ms'][m] for m in methods],color=colours);ax.invert_yaxis();ax.set_xlabel('Complete resident inference · median host ms',color='white');ax.set_title(row['case']+' · all five backends',color='white');ax.tick_params(colors='white');ax.spines[['top','right']].set_visible(False);fig.text(.02,.01,'7 technical blocks · same outputs/FP32 · interrupted recovery qualified · not independent replication',color='#b2c1dd',fontsize=9);fig.tight_layout(rect=(0,.05,1,1));buf=io.BytesIO();fig.savefig(buf,format='png',dpi=100);plt.close(fig);buf.seek(0);images.append(Image.open(buf).convert('RGB'))
    target=ROOT/'docs/animations/advanced_GPU_backends.gif';images[0].save(target,save_all=True,append_images=images[1:],duration=1400,loop=0)
    provenance=dict(source_receipt_sha256=hashlib.sha256((folder/'receipt.json').read_bytes()).hexdigest(),source_plan_sha256=hashlib.sha256((ROOT/'docs/research/RENDER10_benchmark_plan.json').read_bytes()).hexdigest(),gif_sha256=hashlib.sha256(target.read_bytes()).hexdigest(),frames=7,not_inference_FPS=True);(ROOT/'docs/animations/advanced_GPU_backends_provenance.json').write_text(json.dumps(provenance,indent=2)+'\n',encoding='utf-8');print(json.dumps({k:summary[k] for k in ['status','rows','gates','original_rows_preserved','old_rows_repeated']}))
if __name__=='__main__':main()
